<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Passwords must have at least one non alph_e3847b</name>
   <tag></tag>
   <elementGuidId>22282836-bc69-4b3e-a642-b2e67d3a9d27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>504fdd3e-e8f3-4e8d-910d-8f625d7b23d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>bf4e323f-c6c3-4623-9b06-ff2c14f3bdfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-1</value>
      <webElementGuid>df642b27-1c5e-4ef9-8846-4bd39f18394d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Passwords must have at least one non alphanumeric character, one digit ('0'-'9'), one uppercase ('A'-'Z'), one lowercase ('a'-'z'), one special character and Password must be eight characters or longer.</value>
      <webElementGuid>46fc87cd-1a51-4a21-b225-13c9df3be2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name&quot;)</value>
      <webElementGuid>bc8c1fb8-a2a1-489d-ba4b-f7d916c36ae1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='name']</value>
      <webElementGuid>190c90c7-b980-4b49-b0b7-612a57b59907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='output']/div/p</value>
      <webElementGuid>70bd3a98-1434-483d-9c0c-d568a4d6ee57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Login'])[1]/following::p[1]</value>
      <webElementGuid>a912c99e-57d3-48c7-b038-3fe7d2dc84b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[2]/following::p[1]</value>
      <webElementGuid>7057f09e-c492-476c-8fd4-0cdf567de832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::p[1]</value>
      <webElementGuid>5efa3716-71e9-486c-977d-aa1a9e9f488f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'name', '&quot;', ')')])[1]/preceding::p[1]</value>
      <webElementGuid>097a5b5e-cb7d-416b-98dc-e53328a80e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>3cf12742-aa52-48e3-964e-8af8c829b14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'name' and (text() = concat(&quot;Passwords must have at least one non alphanumeric character, one digit (&quot; , &quot;'&quot; , &quot;0&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;9&quot; , &quot;'&quot; , &quot;), one uppercase (&quot; , &quot;'&quot; , &quot;A&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;Z&quot; , &quot;'&quot; , &quot;), one lowercase (&quot; , &quot;'&quot; , &quot;a&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;z&quot; , &quot;'&quot; , &quot;), one special character and Password must be eight characters or longer.&quot;) or . = concat(&quot;Passwords must have at least one non alphanumeric character, one digit (&quot; , &quot;'&quot; , &quot;0&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;9&quot; , &quot;'&quot; , &quot;), one uppercase (&quot; , &quot;'&quot; , &quot;A&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;Z&quot; , &quot;'&quot; , &quot;), one lowercase (&quot; , &quot;'&quot; , &quot;a&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;z&quot; , &quot;'&quot; , &quot;), one special character and Password must be eight characters or longer.&quot;))]</value>
      <webElementGuid>730848a5-2224-4613-b350-e5768bcceb28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
