<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_private</name>
   <tag></tag>
   <elementGuidId>3fb11f44-a0b4-4b14-81e5-091b5aa03604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='result']/span[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e26804b9-1e1f-4382-b0e1-4d19ff63f938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-success</value>
      <webElementGuid>22dea43c-e87f-4e29-9b14-003dd3ca2e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>private</value>
      <webElementGuid>a8669f4f-f3c9-442b-8be7-de71db3d97b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result&quot;)/span[@class=&quot;text-success&quot;]</value>
      <webElementGuid>25a87719-3d3a-483b-b160-d4af6011f71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>58dedb3d-fe6a-407b-85a2-1ce09345b245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-success</value>
      <webElementGuid>ae63cb5e-13ce-4307-ab03-1ed539ae399e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>private</value>
      <webElementGuid>34b9a51b-db9a-4488-8f0a-303bfde48100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result&quot;)/span[@class=&quot;text-success&quot;]</value>
      <webElementGuid>7dc6f2f6-ce6b-4b85-bd63-d04e3d918afc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='result']/span[13]</value>
      <webElementGuid>baa10f18-ce99-4094-a96d-0c32e9a70249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='public'])[1]/following::span[1]</value>
      <webElementGuid>bc76f8b3-d526-40b7-9e21-081a52dd28e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='office'])[1]/following::span[2]</value>
      <webElementGuid>5d074823-b1ef-4d29-aa56-e013cf105358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='classified'])[1]/preceding::span[1]</value>
      <webElementGuid>a414b9db-0929-470d-9927-c76a7c702be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='general'])[1]/preceding::span[2]</value>
      <webElementGuid>a753cfa7-658b-4748-a1e6-e1cfbc707efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='private']/parent::*</value>
      <webElementGuid>d4ec0f76-58f8-406a-9a64-efdfa9b2cb89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[13]</value>
      <webElementGuid>bc0222b0-df6b-452f-b3da-a05fbc975a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'private' or . = 'private')]</value>
      <webElementGuid>d9280ec6-c5b5-4a5a-9012-1b97a2807323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
