<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_home</name>
   <tag></tag>
   <elementGuidId>85a27043-f116-4746-ab27-45f018552d1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='result']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e6c19d6e-abd5-45af-b444-58dd08de9e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-success</value>
      <webElementGuid>8ed1ae90-365a-413c-80f3-93dc2051f2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>home</value>
      <webElementGuid>86dc08d8-f06b-41b6-9550-94631b5bdd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result&quot;)/span[@class=&quot;text-success&quot;]</value>
      <webElementGuid>6d71eb36-80da-488d-8d05-3524978ed73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2b528580-bd01-4fb6-9e10-cff647513bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-success</value>
      <webElementGuid>247492e4-9f92-44b4-be20-b52bd05e8d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>home</value>
      <webElementGuid>0d72ede5-5830-49ab-a697-982333f1f558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result&quot;)/span[@class=&quot;text-success&quot;]</value>
      <webElementGuid>9b4c0a4a-b50c-464d-b8d7-71f6d889bc94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='result']/span[2]</value>
      <webElementGuid>44dec9b2-da9e-43ac-a349-bb5b13ccdda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have selected :'])[1]/following::span[1]</value>
      <webElementGuid>0d025f1d-5742-4d86-b4bf-d17078244166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Downloads'])[1]/following::span[2]</value>
      <webElementGuid>15965ba3-7214-468a-9930-38b39aff27c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='desktop'])[1]/preceding::span[1]</value>
      <webElementGuid>a9d977d2-8980-4baa-a4d1-5edde7df8012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='notes'])[1]/preceding::span[2]</value>
      <webElementGuid>5f13c3fe-5a7e-40ba-87dd-e2009fd70044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='home']/parent::*</value>
      <webElementGuid>c0d6d03a-daca-4a78-b21d-2fd0c5a99159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>a87db6d2-d7cb-4b6b-9262-8b08f0678707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'home' or . = 'home')]</value>
      <webElementGuid>a7b79995-f022-4f79-a845-6d36b7932b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excel File.doc'])[1]/following::span[2]</value>
      <webElementGuid>eae4719d-fd9f-4201-9d77-13d3eac9a9cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
